<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251126083242 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE distance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, distance DOUBLE PRECISION NOT NULL, station_parent_id INT NOT NULL, station_child_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1C929A81F0FEA46B ON distance (station_parent_id)');
        $this->addSql('CREATE INDEX IDX_1C929A8151F8184D ON distance (station_child_id)');
        $this->addSql('CREATE TABLE station (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, short_name VARCHAR(255) NOT NULL, long_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE distance ADD CONSTRAINT FK_1C929A81F0FEA46B FOREIGN KEY (station_parent_id) REFERENCES station (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE distance ADD CONSTRAINT FK_1C929A8151F8184D FOREIGN KEY (station_child_id) REFERENCES station (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE distance DROP CONSTRAINT FK_1C929A81F0FEA46B');
        $this->addSql('ALTER TABLE distance DROP CONSTRAINT FK_1C929A8151F8184D');
        $this->addSql('DROP TABLE distance');
        $this->addSql('DROP TABLE station');
    }
}
