<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251204104628 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE analytic_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FB57EF177153098 ON analytic_code (code)');
        $this->addSql('CREATE TABLE analytic_distance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, distance_km DOUBLE PRECISION NOT NULL, analytic_code_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A6BD86B5D8F0CFE3 ON analytic_distance (analytic_code_id)');
        $this->addSql('ALTER TABLE analytic_distance ADD CONSTRAINT FK_A6BD86B5D8F0CFE3 FOREIGN KEY (analytic_code_id) REFERENCES analytic_code (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE analytic_distance DROP CONSTRAINT FK_A6BD86B5D8F0CFE3');
        $this->addSql('DROP TABLE analytic_code');
        $this->addSql('DROP TABLE analytic_distance');
    }
}
